networks:
  net:
    driver: bridge

services:
  # database
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: restWallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: 'postgres-container'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d restWallet"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - net

  # Redis service
  redis:
    image: redis:7
    container_name: 'redis-container'
    ports:
      - 6379:6379
    networks:
      - net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 4G
    container_name: 'restWallet-container'
    restart: unless-stopped
    hostname: server
    env_file:
      - config.env
    ports:
      - 8080:8080
    command: ["/app"]
    depends_on:
      - postgres
      - redis
    networks:
      - net

volumes:
  pgdata:
